name: "Bug Report"
description: "Report a bug with the Smart Connections plugin"
title: "[Bug]: <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        A clear and concise description of the problem.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem.
      placeholder: "e.g. When I enable Smart Connections, Obsidian freezes."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Open Obsidian
        2. Enable Smart Connections
        3. Click 'Connect'
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The plugin should..."
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead..."
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11, macOS 13.4, Ubuntu 22.04"
    validations:
      required: false
  - type: input
    id: obsidian_version
    attributes:
      label: Obsidian Version
      placeholder: "e.g. 1.8.10"
    validations:
      required: false
  - type: input
    id: plugin_version
    attributes:
      label: Smart Connections Version
      placeholder: "e.g. 2.5.17"
    validations:
      required: false
  - type: input
    id: ai_provider
    attributes:
      label: AI Provider/Model
      placeholder: "e.g. OpenAI GPT-4, Ollama – Llama2 7B"
    validations:
      required: false
  - type: textarea
    id: other_plugins
    attributes:
      label: Other Plugins
      placeholder: "List other enabled plugins or \"none\""
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Screenshots or Console Logs
      description: Attach screenshots or paste logs if applicable. You can also drag and drop files here.
      render: shell
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information.
    validations:
      required: false
